name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发 workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          ref: master  # 检出 master 分支

      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/ACL4SSR/ACL4SSR.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master --strategy-option='ours'

      - name: Push changes to fork
        run: git push origin master  # 推送到你的 master 分支
